name: Auto approve PR
description: ""

inputs:
  github-token:
    description: github token used for the auto approve PR action
    required: true

runs:
  using: "composite"
  steps:
    - uses: hmarr/auto-approve-action@v4
      with:
        review-message: "Auto approved automated PR"
        github-token: ${{ inputs.github-token }}
