name: Test to commit changes and make PR

on:
  workflow_dispatch:

permissions:
  contents: write
  actions: write
  pull-requests: write

jobs:
  make-chage-and-PR:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Create Branch
        run: |
          git fetch
          git checkout -b pr_update
          git branch --set-upstream-to=origin/pr_update pr_update || exit 0
          git pull -ff

      - name: Edit file
        run: |
          echo "change to file" >> test.txt

      - name: Commit changes and commit PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "GitHub Actions Automation"
          git config user.email "<>"
          git commit -am "Updated Service/Cluster Information" || exit 0
          git push --set-upstream origin pr_update
  
          pr_url=$(gh pr create \
          -B main \
          -H pr_update \
          --title 'Update of Service/Cluster Information' \
          --body 'Created by Github action') || exit 0

          echo "PR_URL=${pr_url}" >> "$GITHUB_ENV"

      - name: test pr output
        run: |
          echo "PR with jq: $(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")"
          echo "PR url: ${PR_URL}"
          pr_number=$(echo "${PR_URL}" | grep -o -E '[0-9]+$')
          echo "PR number: ${pr_number}"

      # - name: auto approve
      #   uses: matthew-lewis20/auto-pr-merge-testing/.github/actions/auto-approve-pr@main
      #   with:
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
      #     # pr-number: ${{ github.event.client_payload.pull_request.number }}
