name: testing approving PRs

on:
  pull_request:
    branches:
      pr_update
    types: [opened]
    # types: [auto_merge_enabled]

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    if: github.actor == 'github-actions'
    permissions:
      pull-requests: write
    steps:
      - uses: hmarr/auto-approve-action@v4
        with:
          review-message: "Auto approved automated PR"
          github-token: ${{ secrets.GITHUB_TOKEN }}

